# Generated by Django 3.0.3 on 2020-08-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Club_User',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('fa_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(default='Our Club rocks!')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('coordinatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_coordinator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(through='club_accounts.Club_Member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='club_member',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='club_accounts.Club_User'),
        ),
        migrations.AddField(
            model_name='club_member',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='club_member',
            unique_together={('club_name', 'users')},
        ),
    ]
