# Generated by Django 3.0.3 on 2020-08-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club_user',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='club_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='club_user',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='club_user',
            name='coordinatorid',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='is_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club_user',
            name='description',
            field=models.TextField(default='Our Club rocks!'),
        ),
        migrations.AddField(
            model_name='club_user',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='club_user',
            name='fa_name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='club_user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_user',
            name='name',
            field=models.CharField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_user',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='none', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='club_accounts.Club_User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club_name', 'users')},
            },
        ),
        migrations.AddField(
            model_name='club_user',
            name='members',
            field=models.ManyToManyField(through='club_accounts.Club_Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
